#!/bin/sh

dunst &
lxpolkit &
compton -f -c &
nm-applet &
nitrogen --restore &
redshift-gtk &
xautolock -locker wm-lock.sh &

# And last but not least we start fluxbox.
# Because it is the last app you have to run it with ''exec'' before it.

exec fluxbox
# or if you want to keep a log:
# exec fluxbox -log "/home/isaque/.fluxbox/log"
