#!/bin/sh

# Services
pulseaudio &
dunst &
lxpolkit &
compton -f -c &

# Wallpaper
xrandr --output Virtual-1 --mode 1366x768
nitrogen --restore &

# Systray
nm-applet &
redshift &
sleep 10 && volumeicon &

# Fluxbox
exec fluxbox
