#!/bin/sh

# Services
xfce4-power-manager &
pulseaudio &
dunst &
lxpolkit &
compton -f -c &

# Wallpaper
nitrogen --restore &

# Systray
nm-applet &
redshift &
sleep 10 && volumeicon &

# Lock
xautolock -time 30 -corners 000- -locker wm-lock.sh &

# Fluxbox
exec fluxbox
